### ISSUE TITLE
Add Contribution.md file 

### ISSUE THREAD

**Issue by akanshbende** [surajsharma14/Web-Dev-Project-for-Hacktoberfest2023#13]
Add Contribution.md file for this repo other you will be disqualified from this this hacktober fest

[https://hacktoberfest.com/participation/](url)

read this carefully.

**Comment by nrhitik** [comment]
I would like to work on this issue. Could you please assign me this issue.

**Comment by Gyanendra-Verma** [comment]
I want to contribute, kindly assign this to me @surajsharma14

**Comment by itzanway** [comment]
please assign this task to me under hacktoberfest
